---
abstract: 'Static Utility Methods'
author:
  - 'Pano Papadatos <pano@heypano.com>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132830'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-Pano-Util
provides:
  Acme::Pano::Util:
    file: lib/Acme/Pano/Util.pm
    version: 0.01
resources:
  license: http://www.perlfoundation.org/artistic_license_2_0
version: 0.01
